# Generated by Django 4.2.6 on 2023-12-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='المنصب')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العضو')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الإسم')),
                ('positive', models.BooleanField(default=True, verbose_name='موجب')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('t_date', models.DateField(verbose_name='تاريخ الحوالة')),
                ('ref', models.CharField(max_length=150, verbose_name='الرقم المرجعي')),
                ('bank', models.CharField(max_length=50, verbose_name='البنك')),
                ('remarks', models.TextField(verbose_name='ملاحظات')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='familyTrust.member', verbose_name='المرسل')),
                ('t_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='familyTrust.member', verbose_name='المستقبل')),
                ('t_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyTrust.transactiontype', verbose_name='نوع الحوالة')),
            ],
        ),
    ]
