# Generated by Django 4.2.6 on 2023-12-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyTrust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='installments',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='ref',
        ),
    ]
